package.json

I ran `npm run build` (and `watch`) for the first time, and was notified that the `tablesort` package was missing.
```sh
npm install --save tablesort
```
et voilà!

add tablesort to dependencies

---

openfecwebapp/data_mappings.py
openfecwebapp/tests/data_mappings_test.py

Candidates need to be associated with the state of the office they are running for and not where their office is located.

Fix state mapping

---

__init__.py
openfecwebapp/api_caller.py
requirements.txt

This PR adds support for a `--cached` flag that enables caching of API calls, facilitating a much faster frontend development workflow. You can run it like so:
```sh
python __init__.py --cached
```
I *almost* put the cache installation code in `__init__.py`, but ended up moving it to `api_caller.py` so that all of the request-specific stuff lived there, which makes it simpler to modify how caching is enabled if we were to ever move away from using `requests` for some reason. Happy to entertain another way of doing this, or to use `argparse` instead of just sniffing `sys.argv`.

add --cached flag to cache API requests

---

openfecwebapp/data_prep/candidates.py
openfecwebapp/tests/mock_data.py

Grabbing the office title from the candidate's object instead of the primary committee's type.
Won’t work until #444 is merged

Populating candidate['office'] with the correct info

---

package.json

When running `npm run sass-build` was getting the error:
```
> openfec-web-app@0.0.0 sass-build /Users/msegreto/Developement/openFEC-web-app
> sass static/styles/sass/:static/styles/
Errno::ENOENT: No such file or directory @ rb_sysopen - static/styles/sass/
Use --trace for backtrace.
npm ERR! openfec-web-app@0.0.0 sass-build: `sass static/styles/sass/:static/styles/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openfec-web-app@0.0.0 sass-build script.
npm ERR! This is most likely a problem with the openfec-web-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sass static/styles/sass/:static/styles/
npm ERR! You can get their info via:
npm ERR!     npm owner ls openfec-web-app
npm ERR! There is likely additional …
```

Fixes `npm run sass-build` command

---

__init__.py
openfecwebapp/api_caller.py
openfecwebapp/data_prep/financial_summaries.py
openfecwebapp/tests/data_prep/financial_summaries_tests.py
openfecwebapp/tests/mock_data.py
openfecwebapp/views.py
templates/candidates-single.html
templates/committees-single.html
templates/partials/committee-summary.html
templates/partials/financial-summary.html

Notes:
- Ignore the zero indices selections for templating primary committees. This will change once we have election cycle choosing implemented
- Yup, is meant to remove a lot of code. Its not an accident.

Moving the reports and totals data over to new endpoints

---

__init__.py
openfecwebapp/api_caller.py
openfecwebapp/tests/selenium/base_test_class.py
openfecwebapp/tests/selenium/single_candidate_page.py
static/js/modules/filters.js
templates/candidates-single.html

- Adds a new route: candidate/id/electionCycleYear
- Adds Selenium test to test for contents of election cycle drop down
- changes the candidate used in the test to one that has multiple cycles
- Extend the Chosen JS module to init Chosen on the year drop down
Issue: 18F/openFEC#489

Adds election cycle picker to candidate pages

---

openfecwebapp/tests/selenium/base_test_class.py
openfecwebapp/tests/selenium/candidates_list_page_test.py
openfecwebapp/tests/selenium/committees_list_page_test.py
openfecwebapp/tests/selenium/error_page_test.py

Miscellaneous small changes to make Selenium tests pass in Chrome / Firefox.
* Submit forms using `form.submit()` rather than `input.send_keys(ENTER)`
* Better cross-browser behavior (i.e. doesn't break Firefox)
* Remove `time.sleep` calls
* If waits needed, prefer using Selenium explicit wait
* Ignore SSL errors when using PhantomJS
* Allow user to select Selenium webdriver via FEC_SELENIUM_DRIVER
* Fix a failing test

Miscellaneous updates for Selenium tests.

---

.travis.yml

Looks like Travis builds are currently running Python 2.7. This is the boilerplate from Travis's default Python config file.

Use python3.4 in CI builds.

---

Procfile
__init__.py
newrelic.ini
requirements.txt

I got new relic working on the test instance. Still need to up the security settings.

[wip] Newrelic

---

openfecwebapp/data_prep/committees.py

Just screening out doubles as a temporary fix
Underlying issue will be dealt with in upcoming API re-factor
closes #628

compensating for multipliable candidates being returned

---

templates/candidates-single.html

Temporary fix to hide authorized committees from the candidate header. We can add them back in later.

Commenting out authorized committees in the header

---

templates/partials/committee-charts.html

Reports and totals are returned from the API in descending chronological order, but we want to draw charts in ascending order.
[Resolves https://github.com/18F/openFEC/issues/640]

Show financial charts in ascending chronological order.

---

openfecwebapp/api_caller.py

[Resolves https://github.com/18F/openFEC/issues/641]
@LindsayYoung I just saw that you marked this as not a problem, but it's a tiny change anyway. We can close the PR if it's better to wait for quarterly results.

Use consistent limit for reports and totals charts.

---

__init__.py
openfecwebapp/api_caller.py
openfecwebapp/config.py
openfecwebapp/views.py
package.json
static/js/modules/typeahead.js
templates/layouts/main.html

Prefix API URLs with the current API version, starting with `v1`.
Note: Depends on https://github.com/18F/openFEC/pull/665
[Resolves https://github.com/18F/openFEC/issues/44]

Add API version to URLs.

---

.travis.yml

For testing purposes, the encrypted environment variables in the Travis
configuration were built against jmcarp/openFEC-web-app. This patch
builds the keys against 18F/openFEC-web-app instead and should fix Sauce
tests on the upstream repo.
The diffs are pretty opaque, since they swap out one set of encrypted credentials for another. Also, the pull request build should pass, but that doesn't mean builds will pass after merging, since Sauce tests are skipped on pull requests.

Encrypt Travis environment variables against correct repo.

---

.buildpacks
.cfignore
Procfile

Build assets on cloud foundry instead of building locally and uploading.
This simplifies deployment somewhat by offloading the work of asset
compilation from the developer's machine to Cloud Foundry and makes the
whole process just a little more reproducible.
* Symlink .gitignore to .cfignore
* Use both Python and Node buildpacks
* Build assets on `push`

Build assets remotely.

---

openfecwebapp/tests/selenium/candidates_list_page_test.py
openfecwebapp/tests/selenium/committees_list_page_test.py

Update a few Selenium tests to pass with the responsive changes.
@noahmanger with these changes, all selenium tests are passing locally for me.

Fix failing selenium tests.

---

static/styles/_components/_charts.scss
static/styles/styles.css

Uses the simple solution in openFEC#658, removing the labels on the y
axis.

feature/ simple responsive charts

---

templates/committees-single.html

#695
- fixed mislabeled transfers row
- removed rows that were not producing real data
- fixed spelling errors
- Expanded the explanation when no data is shown

Fix errors on committee profile pages

---

static/styles/_components/_charts.scss
static/styles/styles.css

The chart axes disappeared for some reason. Removing the negative
z-index and putting a positive one on the bars solved it.

Removing negative z-index

---

.buildpacks
Gemfile
Gemfile.lock
README.md
gulpfile.js
package.json

* Build sass on Cloud Foundry
* Update README with command names
* Rename npm commands so common commands have shorter names
* `npm run build` builds js and sass
* `npm run build-js` builds js
* `npm run build-sass` builds sass
* `npm run watch` watches js and sass
* `npm run watch-js` watches js
* `npm run watch-sass` watches sass

Miscellaneous improvements to cache busting.

---

static/js/modules/glossary.js
static/js/modules/typeahead.js
templates/partials/glossary.html

When the user selects an option in the glossary typeahead, the
associated text should appear below. A previous bug fix prevented this
behavior, such that selecting an option did not show the glossary text.
This also uses the `typeahead:selected` custom event, which will hopefully be more robust and easier to understand than listening for particular keypress buttons. @msecret could you verify that the bug you fixed in d013e08137e7fb22ae9dea2761375dbe9c645130 is still fixed with this patch? I think it is, but I'm not sure exactly how the glossary was behaving before you fixed it.

Restore glossary search on typeahead select.

---

package.json

Updates Browserify to prevent issues with JSONStream (https://github.com/substack/node-browserify/issues/1249)

Update version of browserify

---

README.md
bin/post-checkout
bin/post-merge
requirements.txt
tasks.py

Add optional post-checkout and post-merge hooks to update dependencies and
compiled assets when underlying dependencies and code change.
After running `invoke add_hooks`, git will automatically check for changes in `requirements.txt`, `package.json`, and all static files on checkout or merge, and install dependencies and/or rebuild compiled assets if the relevant source files are different. The hooks are optional, so nobody would have to use them if they didn't want to.

Add optional hooks for dependency management.

---

static/styles/_base/_forms.scss

Bourbon is deprecating the `box-sizing` mixin because the CSS property
is now well-supported across browsers. Using the mixin throws a warning
with the current version of Bourbon and will error after the next major
release. If we want to support very old browser versions, it's safest to
add `-moz-box-sizing` etc. manually, but this probably isn't necessary.
See https://github.com/thoughtbot/bourbon/blob/86d2147511265db9cdb35b497e195b8c4649ee98/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss#L407-L411 for details.

Don't use deprecated mixin.

---

static/js/modules/filters.js
templates/candidates.html
templates/committees.html
templates/partials/filters/committee-types.html
templates/partials/filters/designations.html
templates/partials/filters/districts.html
templates/partials/filters/election-years.html
templates/partials/filters/office-sought.html
templates/partials/filters/organization-types.html
templates/partials/filters/parties.html
templates/partials/filters/states.html

By default, `<button>` elements have type `"submit"`, such that pressing
Enter on a form element triggers that button. This means that pressing
Enter when focusing on the candidate or committee name input triggered
the associated remove button, clearing the input. This patch adds the
correct button type of `"button"` to buttons that should not trigger a
form submit.
[Resolves https://github.com/18F/openFEC/issues/669]

Fix types of remove buttons.

---

.travis.yml
tasks.py

Because Travis checks out commits in detached HEAD mode, checking the name of the active branch doesn't work. This patch adds an optional `branch` override before resorting to checking the active branch and passes `$TRAVIS_BRANCH` to that option.
Thanks @arowla for help debugging. Let's see if it works this time. Once the webapp is deploying successfully, I'll submit the changes to the API side as well.

Handle detached HEAD on Travis builds.

---

.travis.yml

We need to install the Cloud Foundry CLI on Travis for commands like `cf push` to work. Sadly, we lose the ability to use containerized builds, but we need `sudo` to install the CF package.

Install Cloud Foundry CLI.

---

templates/partials/committee-summary.html

The term labels were mislabled here so the definitions weren't showing up.

fixing glossary definitions

---

static/styles/_components/_charts.scss
templates/partials/committee-charts.html

We should be using reports data for the Receipts and Disbursements chart, so this does that.
Eventually we'll want to filter these to just be the ones in the current two year period and show more than just the last four, but that can happen later.

Chart data from reports

---

openfecwebapp/api_caller.py
openfecwebapp/views.py

The candidate summary view was previously making two calls to the same API endpoint to fetch candidate information. This patch drops the redundant second call. This should make the candidate summary page load a bit faster.

Remove a redundant API call.

---

static/js/modules/filters.js
templates/candidates.html
templates/committees.html

This patch passes the name search value as "q" instead of "name",
meaning that we use the full-text search on candidate and committee
names instead of the stricter `ILIKE` used by "name". Practically, this
means that searching for "nancy pelosi", "pelosi nancy", or "pelosi,
nancy" will all yield Nancy Pelosi, which is what I think users will
expect.
One side effect of this proposal is that searching for a
candidate's FEC ID will also find that candidate, since the full-text
search includes both name and ID. If this is a problem, we can fix it on
the backend, but I don't think it's a cause for concern.
[Resolves https://github.com/18F/openFEC/issues/777]

Use full-text search for committee and candidate search fields.

---

templates/partials/committee-report-house-senate.html
templates/partials/committee-report-pac-party.html
templates/partials/committee-report-presidential.html
templates/partials/committee-totals-house-senate.html
templates/partials/committee-totals-pac-party.html
templates/partials/committee-totals-presidential.html

Fixes erroneous null values on net contributions for PAC and party
committees pointed out by FEC.
Recommended pairing: https://github.com/18F/openFEC/pull/801

Use harmonized reports names as updated in API.

---

static/js/modules/terms.json
static/styles/_components/_figures.scss
templates/partials/committee-charts.html
templates/partials/committee-summary.html

Addresses 18F/openFEC#822 and also changes the chart key labels to be "Total Receipts, Total Disbursements, Ending Cash on Hand and Debt".

fixing cash on hand labels and chart key

---

__init__.py
templates/macros/charts.html
tests/test_utils.py

For some monthly filings, report dates currently display as e.g. "01/15
- 01/15", which can be confusing (why does the date repeat?). This patch
checks for duplicate dates and only shows one date in that case. Logic
is also moved from templates to a filter, which is also tested.

Hide duplicate dates in charts.

---

__init__.py
templates/committees-single.html
templates/partials/committee-summary.html

- Added check in template to make sure we don't try building a
non-existent link

Changed FEC PDF links to be built by a filter

---

templates/candidates-single.html
templates/committees-single.html

[Resolves #851]
The `title` filter capitalizes the first letter of each word and lower-cases the rest. Not what we want for committee or candidate names.

Preserve casing on committee titles.

---

__init__.py
templates/partials/committee-stats.html
templates/partials/financial-summary.html

We use the `next_cycle` filter to generate the `history` query parameter
for the candidate detail page. The filter is meant to get the next
active cycle greater or equal to the specified cycle. This patch handles
the edge case in which no such cycle is found, in which case we should
simply use the latest active cycle. This fixes some errors on Jeff
Flake's candidate page.

Generate correct history parameter when next cycle is not available.

---

static/js/modules/search.js
templates/partials/search-bar.html

Tiny patch to make the placeholder text consistent between the search bar's default state and when the js changes it on select change. 
Also, now changing the select will change the aria label.

Making placeholder text consistent

---

templates/committees-single.html

Due to a typo in the committee detail template, addresses are currently
hidden for committees that are not associated with a candidate. This
patch moves the relevant `endif` to the right place.
h/t @andrewmaier

Always show committee address.

---

templates/committees-single.html

When there is no information for a candidate/committee, the user won't
want to see any chart bar which confirms a lack of information.

Summary charts should not display chart for None

---

openfecwebapp/views.py
templates/partials/committee-summary.html
templates/partials/financial-aggregates.html
templates/partials/financial-summary.html

When a candidate has multiple authorized or principal committees, users
should see aggregated receipts, cash on hand, etc., across all such
committees before the details for each committee. This patch shows these
aggregate on the candidate detail page, but only when the candidate has
multiple authorized committees.
@dcpcc1967 and @jwchumley: Aggregated cash on hand and debt are different from the current FEC site. The logic implemented here simply adds up cash and debt for the most recent report for all relevant committees; it looks like FECViewer is picking a single committee and using its most recent figures, but it's not clear how that committee is chosen. Figures for receipts and disbursements have been identical for the examples I've looked at.
The proposed layout looks like this …

Aggregate committee financials for multiple authorized committees.

---

__init__.py
templates/committees-single.html
templates/macros/null.html
templates/partials/committee-charts.html
templates/partials/committee-summary.html
templates/partials/financial-aggregates.html

Putting HTML in a string literal in the `currency` filter was breaking
tests. It's also not ideal, since it requires using the `safe` filter,
and unsafe content could potentially leak through. This patch restores
the behavior of the `currency` filter and moves the markup for the "None"
element to a macro. This also applies the new `null` macro to other uses
of the `currency` filter.

Move HTML markup for "None" to macro.

---

__init__.py
requirements.txt

Serve compressed assets to clients that accept gzip encoding. This patch
uses a fork of flask-compress that caches compressed responses by SHA1
to avoid re-zipping files.
We may still want to offload this work to S3 / CloudFront in the future, but this is a quick implementation that should significantly reduce load times.

Compress static assets.

---

Procfile
manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
openfecwebapp/setenv.py
tasks.py

Add blue-green deploys.

---

__init__.py
openfecwebapp/config.py

Immediate use case: when running on Vagrant, we want to use one API URL
internally (localhost:5000) and another externally (localhost:5001).

Allow different API URLs for internal and external use.

---

static/js/modules/glossary.js
static/styles/_components/_glossary.scss

Sometimes the `data-term` attributes are capitalized, and sometimes
not, and list.js wasn’t returning anything if the capitalization didn’t
match. So I just forced everything to lowercase.
Also includes a small style fix to the glossary.
Addresses https://github.com/18F/openFEC/issues/947

Fixing glossary look ups

---

static/js/init.js
static/js/modules/glossary.js

[Resolves #872]
[Resolves #934]

Close open navigation items with escape.

---

__init__.py
openfecwebapp/api_caller.py
static/js/modules/filters.js
templates/candidates-single.html

Also discard the now-unnecessary `history` query parameter used for the
candidate detail page. Since candidates now have history records for all
election cycles between their first and last elections, the `history`
parameter and associated logic is no longer necessary.
Depends on https://github.com/18F/openFEC/pull/933.

Use updated nested history endpoints from API.

---

templates/layouts/main.html

@noahmanger what do you think?

moving 2nd line of beta warning to h3

---

templates/layouts/main.html

- Linking to the right github repo
- adding a link to API in footer

[WIP] The production API needs to be updated before this is merged.

---

templates/layouts/main.html
templates/partials/javascript-warning.html

When a user doesn't have javascript enabled, they should see a warning
that some functionality will not work, and be informed how to enable
javascript.
I used the site http://enable-javascript.com/ as a link for explaining
how to enable it, @emileighoutlaw, please check the content.

Javascript disabled warning

---

__init__.py
templates/committees-single.html
templates/macros/charts.html
templates/partials/committee-charts.html

* Hide bars with null value.
* Hide series with all null values.
* Hide group series with all null series.
This is a follow up on https://github.com/18F/openFEC/issues/896, which
was partially resolved by #229.

Handle null values in all charts.

---

.travis.yml

Currently, we run webapp tests under three configurations: with no sauce labs (just the unit tests), with sauce labs + firefox, and with sauce labs + chrome. But all three configurations use the sauce connect addon, meaning each build uses up three sauce tunnels. This patch doesn't use a sauce connect tunnel for the sub-build that doesn't use sauce.

Only use sauce connect for browser builds.

---

static/styles/_components/_alerts.scss

[Resolves #963]
@noahmanger not sure why we were overriding the `display: none` associated with `[aria-hidden="true"]` in the first place.

Hide beta banner on close button.

---

__init__.py
tests/test_utils.py

Since we aren't exposing data before 1979.

Hide pre-1980 cycles in election cycle pickers.

---

static/styles/_base/_buttons.scss
static/styles/_components/_modals.scss
templates/layouts/main.html

This moves the close button to the upper right where it belongs ;)

Repositioning mobile nav close button

---

static/js/modules/tables.js
static/styles/_layout/_data-view.scss

Quick fix to re-align the null checkbox and move the paginate controls to the right.

moving null checkbox

---

static/styles/_components/_side-panel.scss
templates/partials/filters/container.html

This fixes the filter panel on mobile by creating a new component
element. It does not fix the template organization problem. This
was done to make the merge conflict in #337 easier as it's less code
that will be modified.

Fix the filter panel, not the template org

---

templates/donations.html
templates/expenditures.html
templates/partials/filings-tab.html
templates/search.html

This adds links to the home page for purpose of usability testing:
It's ugly, but will work for now. Also, this doesn't do the work of renaming the template files / URLs to "Receipts" and "Disbursements" but I was afraid of opening that can of worms.

Adding links to receipts, expenditures and filings from home

---

__init__.py
static/js/modules/filters.js
static/styles/_components/_entity.scss
static/styles/_layout/_layout.scss
templates/candidates-single.html
templates/committees-single.html
templates/partials/cycle-select.html
templates/partials/disbursements-tab.html
templates/partials/filings-tab.html
templates/partials/financial-summary.html
templates/partials/receipts-tab.html
tests/test_utils.py

Based on #351, I wanted to come up with a better, more consistent place for the cycle select. So this patch does just that. @jenniferthibault can you review to make sure this captures what we discussed yesterday?
There are now cycle selects on any tab where you can control the cycle (so everything except "Filings"), and changing one changes them all.
*Also:* I moved the logic on the Candidates and Committees page so that even if there's no records, you still see the "financial summary" section heading and explanatory text.
*To do:* Once we have persistent tab URLs, you'll no longer be bumped to the first tab upon changing the select on the second or third tab.

Cycle select update

---

static/js/pages/committee-single.js
static/styles/_components/_dropdowns.scss
static/styles/_components/_filters.scss
static/styles/_layout/_data-view.scss
templates/partials/filings-tab.html
templates/partials/filters/amendment-indicator.html
templates/partials/filters/primary-general.html
templates/partials/filters/report-type.html

1. Tightens up the filters on the filings table on committee pages
2. Moves the table page controls below tables on the committee page. @jenniferthibault this was the pattern you were using on election pages, correct?

Styling committee filing filters

---

static/js/modules/typeahead.js
static/styles/_components/_search-bar.scss
templates/layouts/main.html
templates/macros/search.html
templates/partials/search-results-controls.html
templates/search-results.html
templates/search.html
tests/selenium/search_results_test.py

This makes the radio buttons the only way to change the search type. Changing the search type now works as expected.
Also, this hides the header search on the search results page, as well as changes the way you hide the header (now just set a variable on the template `hide_header_search = true`).
(Wasn't sure the style for template variables like this, so can change to fit the convention.)

Removing the search select in favor of radios

---

manifest_dev.yml
manifest_stage.yml
tasks.py

Switch to 18f.gov. See also https://github.com/18F/openFEC/pull/1089.

[dontmerge] Use 18f.gov for SSL termination.

---

static/js/modules/helpers.js
static/js/modules/tables.js
static/js/pages/committee-single.js

I saw an opportunity to help with one of the dev tasks ( #376 ), so I went ahead and did it. This adds links to the amounts in the Receipts and Disbursements tab tables to the itemized transactions that make up the total. So when you click the Facebook total in this table:
It shows the transactions that make up that total:
I tried to code this up in a smart, reusable way, but please let me know if there's anything I should do to tighten it up (I imagine there is).

Adding aggregate links to itemized tables

---

static/js/modules/tables.js
static/js/pages/receipts.js
static/styles/_base/_tables.scss
static/styles/_components/_panel.scss

This UI is to make it easier to understand how to open the table
rows to show the details panel. A new table column was used to
contain the button so that everything fits within data tables
width interface. Additional styles were set from the table scss
as its generally safe to ensure these styles for any icon in the
table.
@noahmanger whats the best way to make the arrows as thick as in
the mockup? Right now they are thinner.

Arrow button on rows for panel

---

static/js/pages/committee-single.js
templates/partials/receipts-tab.html

Use DataTables for contribution size table.

---

static/js/modules/tables.js

Since both the data tables and the tabbing interface can change the
window history, the data tables should only refresh on popState when the
relevant query parameters have changed. Previously, this check was
applied on every table reload; this patch applies the check only on
reloads triggered by the popState event.
[Resolves #433]

Restore paging and sorting.

---

static/js/modules/tables.js
static/js/pages/committee-single.js
static/js/pages/elections.js
static/js/vendor/tablist.js

Add the `onShow` helper, which creates a one-time event listener to do
some work when the specified tab is selected. Also add the
`initTableDeferred` helper, which defers table initialization until the
parent tab is displayed.
@noahmanger this coincidentally fixed #359, which seems to be related to rendering tables in hidden tabs. Now that we don't render the table until the tab is displayed, that behavior goes away.
[Resolves #345]
[Resolves #359]

Load data for tabs on tab selection.

---

tests/selenium/search_results_test.py
tests/selenium/single_candidate_page_tests.py
tests/selenium/single_committee_page_tests.py

Several of our tests assume that certain candidates and committees will
exist, which can cause spurious failures when the test subset changes.
This patch removes a few of these hard-coded dependencies, although
there's more we could do to decouple these tests from the data.

Avoid hard-coded dependencies on test data where possible.

---

.travis.yml

Sometimes installing from npm or pypi fails and breaks the build. This
patch uses `travis_retry` to retry install steps that may fail when
external services are down.

Use `travis_retry` to handle errors on external services.

---

static/js/modules/tables.js
static/styles/_base/_buttons.scss
static/styles/_components/_panel.scss
static/templates/disbursements.hbs
static/templates/receipts.hbs
templates/partials/datatable-modal.html

This adds the button for the pdf image of the current thing on the
panel. This uses special jquery code to set the button href to the
pdf from the receipt/whatever data because the button code is not
part of the actual template being rendered. There could be a lot of
unnecessary duplication if this part of the UI was moved into the
template, so I found it easier to keep it outside with this special
code.

Original image button on panel

---

static/templates/disbursements.hbs
templates/partials/disbursements-filter.html

This expands all disbursement filters and adds more information to the details panel (as well as correct markup):
[Resolves #495]

Updating /disbursements

---

static/js/modules/tables.js

The markup for the hide null input was changed slightly during the move
to the updated styles, which dropped the corresponding parameter from
the API request. This patch updates the table logic to use the current
markup.
[Resolves #493]

Restore hiding null values on sorted columns.

---

static/js/modules/performance.js

Safari defines `window.performance` but not
`window.performance.getEntriesByType`. Attempting to call this
function in debug mode in Safari crashes the page, blocking other JS.
This patch checks for `getEntriesByType` before calling it, and
additionally tightens up `performance.js` to use fewer local variables.
Ping @msecret to take a look when you have time.

Fix JS error in Safari.

---

static/js/modules/maps.js
static/js/pages/committee-single.js
static/js/pages/elections.js

* Add unstyled tooltip for election state maps
* Bring hovered state to front
Part of https://github.com/18F/openFEC-web-app/issues/420
Looks like this, but will look way better after design by @jenniferthibault:

Add basic map tooltips.

---

static/js/modules/filters.js
static/js/modules/tables.js
static/js/pages/candidates.js
static/js/pages/committees.js
static/js/pages/disbursements.js
static/js/pages/receipts.js

Companion PR to https://github.com/18F/fec-style/pull/46
This:
- Adjusts the height of the filter bar to the height of the table by listening to the `draw.dt` event
- If the panel is open and you change the filters, the panel now closes (so I moved the code to hide the panel to a separate function)
- Adds the markup for the loading animation
- Minor column sizing styles
No reason to hold this up, but just noting that the tables still need some work on small screens.

Feature/loading-state & table improvements

---

static/js/modules/filings.js
static/js/modules/tables.js

This patch separates the presentation from the js functionality by creating a new class for rows with panels. (Goes with https://github.com/18F/fec-style/pull/60)

Creates a separate class to control styles

---

static/js/modules/columns.js
static/js/pages/candidates.js
static/js/pages/committees.js
static/js/pages/disbursements.js
static/js/pages/receipts.js

Small patch: when I added padding to cells to prevent bars from running into each other, it made the cells that have the arrows for the details panel hide the arrow icons. This removes that padding from those cells so you can see the arrows.

Removing padding on arrow cells

---

static/js/pages/elections.js
static/templates/comparison.hbs
templates/partials/elections/candidate-comparison-tab.html

A recent patch hid the candidate checkbox dropdown on the election
summary page. This patch restores the dropdown and cleans up the
associated code.
Current behavior on develop:

Restore candidate dropdown.

---

static/js/pages/committee-single.js
templates/partials/datatable-modal.html
templates/partials/filings-tab-committee.html

Limits the filings that show up in the table on the committee page filings tab to those in the current cycle. 
We can discuss if we still need the filters with the shorter list. They might still be useful if you're looking at an older period that has the full range of filings.
[Resolves #424]

Limiting filings on filings tab to the current cycle

---

static/js/pages/committee-single.js
templates/partials/disbursements-filter.html
templates/partials/receipts-filter.html

A few fixes to make filters more consistent coming from the aggregate tables on committee pages:
**/receipts**
- Adds a filter for Contributor Name
- Adds a separate typeahead filter for Committee Name
**/disbursements**
- Adds a typeahead filter for Recipient Committee
- Fixes js to pass the correct variable (`recipient_committe_id`)
[resolves #511]

Adding / fixing filters for committee names

---

static/js/modules/tables.js

Currently, some data table bars with missing values are rendered as
full-width instead of empty. This patch fixes the bug and cleans up the
bar render function.
Current behavior on dev:

Fix data table bars with missing data.

---

static/js/modules/election-lookup.js
static/js/modules/helpers.js
static/js/modules/maps.js
static/js/modules/tables.js
static/js/pages/candidate-single.js
static/js/pages/committee-single.js
static/js/pages/election-lookup.js
static/js/pages/elections.js
tests/unit/modules/election-lookup.js

* Use `helpers.buildUrl` instead of miscellaneous URL builders
* Add trailing slashes to avoid API redirects
We currently a bunch of repeated logic across functions that build URLs. This patch moves most URL building to `helpers.buildUrl.`

Consolidate URL generation logic.

---

static/js/modules/columns.js
static/js/modules/tables.js
static/js/pages/committee-single.js
static/js/pages/elections.js
templates/elections.html
templates/partials/receipts-filter.html

Link election aggregates by size, location, and contributor type to itemized receipts.
@noahmanger: did we want to link the totals in the top election table to itemized receipts and disbursements as well? This patch just covers our custom aggregates so far.
Part of #449.

Link election aggregates to individual transactions.

---

static/js/modules/election-lookup.js

The viewport around Alaska is much too big, as described in #617. This patch adds a manual override to set sensible coordinates and zoom for Alaska.

Add manual override for Alaska viewport.

---

static/templates/electionNoResults.hbs

Styles the message that shows up if the zip code isn't found. @emileighoutlaw how doest this language work for you? Made a slight adjustment from @LindsayYoung 's original.

styling the no results message

---

static/templates/candidates.hbs
static/templates/disbursements.hbs
static/templates/electionZipWarning.hbs
static/templates/receipts.hbs
templates/candidates-single.html
templates/candidates.html
templates/committees-single.html
templates/committees.html
templates/disbursements.html
templates/election-lookup.html
templates/elections.html
templates/partials/committees-table.html
templates/partials/disbursements-filter.html
templates/partials/elections/candidate-comparison-tab.html
templates/partials/elections/outside-spending-tab.html
templates/partials/filings-tab-candidate.html
templates/partials/filings-tab-committee.html
templates/partials/filings-table.html
templates/partials/filters/committee-types.html
templates/partials/hero.html
templates/receipts.html
templates/search-results.html
templates/search.html
tests/selenium/landing_page_test.py

Tightens a small portion of content. Restyles a variety of headers, subheads, and fields to adhere to sentence case capitalization

Content stylings

---

static/js/pages/elections.js
templates/partials/elections/candidate-comparison-tab.html

Part of https://github.com/18F/openFEC-web-app/issues/572. Depends on https://github.com/18F/fec-style/pull/85.
@noahmanger: this is *almost* right. There were a few styles that conflicted with `scrollX` in fec-style, which I'm now overriding for tables with the `scrollX` class. The only remaining issue I see is that the header rows don't exactly line up with the columns sometimes--I think it's related to the value bars in the table. If you have the time / interest to take a look, I'd appreciate it, else I'll pick this up again and see if I can get the last kinks worked out.

Use `offsetX` to handle many candidates in election state table.

---

static/js/pages/candidate-single.js
static/js/pages/committee-single.js
static/js/pages/elections.js

* Browse views (candidates, committees, filings) use paging by number
* Large browse views (receipts, disbursements) use simple paging
* All other tables use simple paging
[Resolves #635]

Use consistent options for paging.

---

static/js/modules/election-lookup.js

Map pin colors are currently all set to gray. This patch restores the
expected pin colors.

Fix regression on election pin colors.

---

static/js/modules/filters.js
templates/partials/filters.html
templates/partials/filters/filter-buttons.html
templates/partials/receipts-filter.html

Based on usability feedback, this adds "Apply filters" and "Clear filters" to the top and bottom of the filter panels. The apply button is basically just a dummy button to get the user to change focus from a text input. The clear button js could maybe be refactored, but it may also make sense to wait and see how if this solves the problem before we optimize.
Resolves https://github.com/18F/openFEC/issues/1170

Adding apply and clear buttons to filters

---

static/js/pages/candidates.js

As discussed in #647, candidate incumbency status is only defined per
election, and not across a candidate's electoral history. Since the
candidate browse view shows summary information about candidates rather
than per-cycle information, it doesn't make sense to show the incumbency
indicator here.
[Resolves #647]

Remove incumbent indicator from browse view.

---

static/js/modules/maps.js
templates/partials/receipts-filter.html

Adds the tooltip to the unique filters.
Adds an additional class to specify that map tooltips should have the arrow below the tooltip.
Depends on https://github.com/18F/fec-style/pull/101
Resolves https://github.com/18F/openFEC-web-app/issues/529

Adding tooltips to filters

---

static/js/init.js
templates/partials/navigation.html

Requires https://github.com/18F/fec-style/pull/102

using class for glossary toggle

---

templates/search.html

Adds correct links to the data landing page. 
- Changed "Top contributions from individuals this year" to "Contributions from individuals this year" because we can't sort by size in the url.
- "All PACs active in 2015-2016" links to show all Lobbyist, Leadership, PAC (non), PAC (qualified), PAC (non-contribution, nonqualified), PAC (non-contribution, qualified)
- "All independent eexpenditure committees active in 2015-2016" links to show all Super PACs, single candidate independent expenditure, and independent expenditor (person or group)
Resolves https://github.com/18F/openFEC-web-app/issues/705

adding links to landing page

---

static/js/modules/election-summary.js
templates/search.html

We won't have conflicting candidate counts and we still have big numbers for context

Counting candidates is hard, lets just show the money

---

templates/macros/filters/date.html
templates/partials/committee/disbursements-tab.html
templates/search.html

This makes for more readable URLs and fixes a bug on back and forward
navigation resulting from conversion between slash- and hyphen-delimited
dates.
[Resolves #713]

Use hyphens for all dates in URLs.

---

static/templates/comparison.hbs
templates/macros/filters/checkbox.html
templates/macros/filters/states.html
templates/partials/filters/committee-types.html
templates/partials/filters/districts.html
templates/partials/filters/election-years.html

Prevent enter keypress from toggling dropdowns. The default "type" of
buttons in most browsers is "submit", which can cause unintended
keyboard interactions if not overridden.

Add button types to dropdown buttons.

---

static/js/init.js
templates/layouts/main.html

Removes the tabindex from `<main>` and implements the skip-nav link from https://github.com/18F/fec-style/pull/113/files

Implementing skip nav

---

static/js/modules/tables.js

Fix a subtle issue such that each render adds a new modal callback to
the table. Instead, on render, remove the previous callback if present
before adding the new one.
Related to https://github.com/18F/openFEC-web-app/issues/734.

Replace existing modal callback with new callback.

---

static/js/modules/tables.js
static/js/pages/candidate-single.js
static/js/pages/committee-single.js
static/js/pages/elections.js

On fetching results from tables without filters, destroy the `DataTable`
instance and add placeholder text if no results found. Note: this patch
uses a placeholder placeholder, which would probably benefit from style
and content review by @noahmanger and @emileighoutlaw.
[Resolves #512]

Replace empty tables with placeholder text.

---

static/templates/electionZipWarning.hbs
templates/404.html
templates/500.html
templates/partials/disbursements-filter.html
templates/partials/filters.html
templates/partials/receipts-filter.html

Styles the disclaimers on receipts and adds the info icon to the "messy data" warning tooltip trigger.
Depends on https://github.com/18F/fec-style/pull/119
Resolves #689 
Resolves #736 
Resolves #633

Styling messages

---

static/templates/comparison.hbs

I just realized I never put this patch in to add the text explaining that candidates on the eleciton comparison tool are ordered by amount raised.
And then with https://github.com/18F/fec-style/pull/120 they will be ordered in columns, instead of rows.
Also adds padding to the controls.
Resolves https://github.com/18F/openFEC-web-app/issues/649
Resolves https://github.com/18F/openFEC-web-app/issues/648
Resolve https://github.com/18F/fec-style/issues/84

Fixing candidate comparison order

---

static/js/pages/committee-single.js
templates/committees-single.html

This removes the "Unique only" flag from links from "Receipts from committees" aggregates. 
Also changes the URL parameter of this tab from "Transfers" to "Between committees".
Resolves https://github.com/18F/openFEC-web-app/issues/751

Removes "is-individual" from links

---

templates/candidates-single.html
templates/committees-single.html
templates/elections.html
templates/partials/candidate/financial-summary.html
templates/partials/committee/financial-summary.html
templates/partials/elections/candidate-comparison-tab.html
templates/partials/loading-tab.html

Hide all tabs initially, showing the selected tab after parsing the
query parameters. Needs style fixes from @noahmanger--see
`templates/partials/loading-tab.html`.
h/t @konklone

Improve behavior on loading tabs by permalink.

---

static/js/pages/committee-single.js

This sets the default text for employer and occupation aggregates to "NOT REPORTED" (using all caps for consistency with the data).
h/t @jenniferthibault

Add default text for aggregate labels.

---

openfecwebapp/utils.py
templates/macros/filters/date.html

Update built-in date filters.

---

templates/macros/disclaimer.html
templates/partials/candidate/other-spending-tab.html
templates/partials/elections/other-spending-tab.html

- On election pages: Adds links to the glossary terms for the other spending table
- On the candidate and election pages: Adds a note explaining what reports are included in the independent expenditures table
- Adds some padding to the disclaimers below tables
Resolves https://github.com/18F/openFEC-web-app/issues/573

Adding other spending explanations

---

__init__.py

Necessary for URL redirects to work behind the proxy.

Respect x-forwarded-host header.

---

.hound.yml
.jshintrc
static/js/init.js

* Set longer max length.
* Update pre-defined globals.
This also reminds me: are we all using jshint locally? Consider this my passive-aggressive reminder to @LindsayYoung and @noahmanger to grab the sublime plugin if you don't already have it. And if you think the linter is being too strict, feel free to update .jshintrc.

Customize linter configuration.

---

templates/search.html

Moves dash from *minus*
to *n dash*— how ranges should
be represented.

Fixes ranges— easy merge

---

openfecwebapp/constants.py
templates/partials/filters/candidate_status.html
templates/search.html

The statutory candidate data is much cleaner, so it makes a good default.
We can just add 'candidate_status=C' to all the links to that page. Is there a better way to handle that default?
I am simplifying this a bit, the full list of codes codes is:
C = Statutory candidate
F = Statutory candidate for future election
N = Not yet a statutory candidate
P = Statutory candidate in prior cycle

Adding a statutory candidate check box

---

templates/partials/committee/between-committees-tab.html
templates/partials/committee/disbursements-tab.html
templates/partials/committee/receipts-tab.html
templates/partials/elections/candidate-comparison-tab.html

Addresses capitalization inconsistency and fixes "compare by," which should be "group by."

Content fixes

---

templates/search.html

This is a quick and dirty re-arranging of the cards and election lookup tool on the data landing page to test it out for testing tomorrow. 
Includes an inline style because it wasn’t worth writing new css for a temporary change :)
Also visually hides the cycle select for now.

Rearranges elements on data landing page for testing

---

__init__.py
manifest_base.yml
manifest_prod.yml
openfecwebapp/config.py
tasks.py

* Remove unnecessary `server_name` configuration (now set by proxy)
* Increase timeout (minification can be slow)
* Set default domain to 18f.gov
* Remove open.api.gov route

Miscellaneous manifest updates.

---

static/js/pages/elections.js

* Use URL helper on election page.
* Delete unused code.

Fix candidate URL on election page.

---

templates/candidates-single.html

Pending changes in https://github.com/18F/openFEC/pull/1278, some null
districts will be represented as "00" rather then `null`. This patch
hides both "00" and `null` districts.

Hide district if 00.

---

templates/layouts/main.html

from fec.gov to FEC.gov
[ci skip]

updates URL capitalization

---

templates/candidates-single.html
templates/committees-single.html

Removes icons from the breadcrumb area on candidate and committee pages, since they felt out of place.
I had made this change a while ago, but I think it was overwritten.

Removing icons from breadcrumbs area

---

templates/partials/candidate/other-spending-tab.html

Adds introductory body text to the other spending tab that shows what the tab is and isn’t. Addresses @emileighoutlaw ’s https://github.com/18F/openFEC-web-app/issues/858
Review:
@noahmanger 
Question: I noticed that the header structure for the Financial Summary tab didn’t match the structure of this Other Spending tab. I made them consistent, but if there was a reason for, please advise :)

Other spending disclaimer

---

static/js/pages/elections.js
templates/partials/candidate/financial-summary.html
templates/partials/elections/candidate-comparison-tab.html

* Remove total receipts and disbursements links.
* Add links to source filings.
[Resolves #873]
This isn't quite ready for merge. Two outstanding questions:
* I've tentatively labeled the column that links to the base filings "Financial reports". @LindsayYoung and @emileighoutlaw, feel free to weigh in with a more precise name if this is too fuzzy.
* I'm not sure what text / icon to use for the new column linking to the F3 filings. Since we're now linking to a browse view of all relevant filings for a candidate, we can't use text like "May Quarterly 2016"--the text will be the same for each row. I'm using the placeholder text of "Link" for now, but that needs to change. Maybe a link-out icon would be useful here.
cc @jenniferthibault @noahmanger

Update URLs and columns in top-level election table.

---

static/js/modules/columns.js

Only show detail panel trigger when form type is one of "F3", "F3P", and
"F3X". Fixes extraneous triggers on less common forms like "F3L".
h/t @noahmanger

Handle miscellaneous F3* forms.

---

static/js/modules/election-lookup.js

Following a recent change in the API, missing values for `state` and
`district` have mostly changed from `null` to "US" and "00",
respectively. This patch checks for all possible missing values upon
receiving data from the API.
To check, verify that searching for elections by zip, state, and district work as expected.
h/t @noahmanger

Handle multiple null values for state and district.

---

static/js/modules/tables.js
static/js/pages/committee-single.js

Since we don't currently expose filters to restrict transctions by null
employer or occupation, we don't have a good way to build links to
itemized browse views for aggregates with null values. This patch omits
links for these aggregate rows.
To verify: browse to a committee detail page, receipts tab, employer or occupation aggregates; there should be the usual links to aggregates for non-null employers and occupations, but no links for null values.
h/t @noahmanger

Skip links on null employer and occupation.

---

openfecwebapp/api_caller.py

When committee history information can't be found from the history
sub-endpoint, use the detail endpoint instead. This is a temporary fix
and should be reverted once the underlying issue described in
https://github.com/18F/openFEC-web-app/issues/875 is resolved.
Depends on https://github.com/18F/openFEC/pull/1295.

Temporarily fetch committee information from detail table.

---

openfecwebapp/views.py
requirements.txt

Necessary for feedback submission via the CMS application. Going
forward, we may want to restrict the origin to beta.fec.gov, but this is
fine for now. This becomes moot if the feedback widget is exported to a
separate application.
Required for https://github.com/18F/fec-cms/pull/98.
cc @LindsayYoung @noahmanger

Allow cross-origin requests to feedback endpoint.

---

templates/layouts/main.html

This makes it consistent with the beta.fec.gov homepage capitalization

Update "looking for" link from "FEC.gov" to "fec.gov"

---

templates/layouts/main.html

No longer adding `.has-banner` to the body.

Removing has-banner calss

---

static/js/modules/tables.js

This patch attempts to fix a longtime issue with permalinks for table
filters. On table initialization, we grab filter values from the query
string and set them in the filter fields. Because some fields change
their inputs (mostly fields with input masks, but potentially other
fields as well), this can trigger a change in the URL. In these cases,
the back button brings the user back to the initial URL, which again
triggers an immediate URL change when the input is changed by the filter
field. This patch sidesteps the issue by using `history.replaceState`
rather than `history.pushState` on load, meaning that we don't push a
new entry to this history.
To verify, enter a URL that will be automatically transformed on load,
such as http://localhost:3000/filings/?min_receipt_date=10/01/1985, …

Replace history on table initialization.

---

README.md

Executing Lindsay's excellent suggestion that we add a specific section to explain the repo users are *currently visiting*. 
Will wait for this one to merge before I move on to other repos, in case anyone has questions/concerns.
@LindsayYoung @jmcarp
[ci skip]

Adds line about what this repo is

---

templates/partials/ie-chart.html

Makes the ie charts and other committee charts sections have the same styling.

Making markup the same as the markup for candidate committee charts

---

__init__.py

Follow-up from taking the password down yesterday. We should use basic auth if credentials are found in the environment, not otherwise; no need to key on `FEC_WEB_TEST` or other envvars.
Note: this isn't urgent--I'm sending as a hotfix because it should be merged into master before the next deploy. Attention @LindsayYoung.

Skip basic auth unless credentials set.

---

templates/layouts/main.html

Adds contact copy for email and github, as determined in https://github.com/18F/openFEC-web-app/issues/866#issuecomment-154172692
Goes with https://github.com/18F/fec-style/pull/174
I can’t seem to get the image code quite right here, and would appreciate help!
Might have to add an image class afterwards for image positioning?
@noahmanger

Adds new footer items for feedback and github

---

.buildpacks
package.json

The Cloud Foundry team recently updated the node buildpack and the
default version of node installed. This causes deployments to fail on
buildpack compilation. This patch pins our node and buildpack versions
to the last known working releases.
Same as https://github.com/18F/openFEC/pull/1347.

[hotfix] Pin buildpacks.

---

.travis.yml
package.json

Installing karma-phantomjs-launcher and its peer dependency, phantomjs,
cause deploys to Cloud Foundry to fail. This patch removes the phantomjs
launcher from the dependencies and manually installs within Travis.

Skip phantomjs install.

---

static/js/modules/election-lookup.js
tests/unit/modules/election-lookup.js

* Correctly render ZIP codes in DC
* Cancel pending AJAX request on new search
* Fix bug such that maps didn't update on selecting a state without
changing search criteria
This fixes a few minor bugs that I noticed on the election search widget. To test manually, verify that the relevant production bugs don't happen with this branch checked out: DC ZIP codes should render, and clicking a state after clicking and zooming out again should re-highlight the state. This one's a little tricky to replicate--you do it like this:
* Open the election search page
* Click on a state
* Zoom out until all states are rendered in color on the map
* Click on the same state again
In production, this *doesn't* re-highlight the state as it should; under this patch, it does.
cc @noahmanger @msecret

Miscellaneous updates to election map.

---

openfecwebapp/api_caller.py

This reverts commit 5758386055e3ded018ea6236978947e585d70fb0.
Note: depends on https://github.com/18F/openFEC/pull/1325, which resolves the underlying issue and obviates the temporary hack we were using in the meantime.

Revert "Temporarily fetch committee information from detail table."

---

templates/search.html

Instead of just hiding the cycle select, use a hidden field.
This way the hidden field doesn’t receive tab focus.
Resolves https://github.com/18F/openFEC-web-app/issues/908

Use hidden field on home election search

---

templates/macros/cycle-select.html
templates/partials/receipts-filter.html

Changing markup so tooltips are now controlled by a trigger button instead of hovering over a label.
Requires https://github.com/18F/fec-style/pull/187

Tooltips now triggered by button

---

openfecwebapp/api_caller.py
openfecwebapp/views.py
templates/partials/candidate/financial-summary.html

Instead of making potentially many separate API calls and aggregating
the results manually, this patch uses the new candidate aggregate totals
endpoint to fetch the desired results in a single request. Note: this
removes the coverage dates under the totals values, since they aren't
part of the new endpoint. We can restore them if necessary, but I think
the link to the relevant filings under the values is sufficient.
Depends on https://github.com/18F/openFEC/pull/1352.
Once this and the corresponding API patch are merged, this work will be the basis of four- and six-year totals aggregates on the candidate page.

Load aggregated candidate totals from API.

---

templates/partials/navigation.html

- Adds the href and removes disabled state on the "Registration and reporting" nav item
- Shows the dropdown nav item for "Campaign finance data home" in order to help people find the data landing page easier 
Still waiting on potential style changes to the nav, but once we have those, this will be good.
Resolves https://github.com/18F/openFEC-web-app/issues/968

[WIP] Activating reporting and registration link

---

openfecwebapp/views.py
templates/candidates-single.html
templates/partials/candidate/financial-summary.html

Currently, viewing off-year periods builds incorrect election titles and
links: for example, viewing Barack Obama in 2010 builds a link called
"2010 Presidential Election". This patch builds the correct election
year and uses it for both the title and link.

Fix election title and link for off-year periods.

---

templates/search-results.html

The tiniest little patch to add the query parameter to the "filter these results" link from search results to browse pages:

Adding query parameter to link to browse pages

---

static/js/modules/columns.js
static/js/modules/tables.js
static/js/pages/candidates.js
static/js/pages/committees.js

Use election years for election years column.
Use the `election_years` field to populate the "Election years" column
in the browse candidates table, and to build the "cycle" query parameter
for links to candidates. This resolves a bug that was discovered during
the latest release such that candidate links pointed to the most recent
matching cycle, which in many cases was later than the most recent
election year, leading to a large number of effectively dead links.
h/t @leahbannon for spotting this

[dontmerge] Hotfix/browse candidates election year

---

__init__.py
templates/partials/elections/candidate-comparison-tab.html

- Adds a `office_code` variable which can be used to build the link to
the candidates browse page
- Adds a link on election pages to view all candidates who’ve filed for
an election
Might make sense to merge until after we've made the "cycle" / "Election years" filter switch, as this will need to change then.
Also, @emileighoutlaw and @jenniferthibault what do you think of language and display as so:
Resolves https://github.com/18F/openFEC/issues/1408

Adding link to candidates page from election

---

static/js/modules/helpers.js
static/js/pages/receipts.js
static/templates/receipts.hbs

As @PaulClark2 explained, the `contbr_id` field for earmarked receipts
describes the earmarking committee and not the contributor. This patch
uses the `contbr_nm` field and hides the `contbr_id` field in these
cases.
[Resolves https://github.com/18F/openFEC/issues/1426]
[Resolves https://github.com/18F/openFEC/issues/1410]
[Resolves https://github.com/18F/openFEC/issues/1308]

Hide committee contributors on earmarked receipts.

---

README.md

I tracked down the default port of the local instances of the site and added it to the readme.

Add URL of local instance of site to README

---

openfecwebapp/views.py
templates/candidates-single.html

Currently, candidate detail pages link to related committees at the
current cycle. On full election views, related committees may have no
data for the selected cycle, leading to a 404. This patch resolves the
404 issue by linking to each related primary committee using the most
recent applicable cycle.
[Resolves https://github.com/18F/FEC/issues/195]
To verify: as described in https://github.com/18F/FEC/issues/195, browse to /data/candidate/P00003392/, and check that both primary committee links resolve. Because "Hillary Clinton for President" last reported in 2014, that link should go to the 2014 cycle; the more recently active "Hillary for America" should go to the 2016 cycle.
cc @LindsayYoung @noahmanger

Link candidate committees to most recent applicable cycle.

---

static/js/modules/helpers.js
static/templates/candidates.hbs
static/templates/committees.hbs
static/templates/disbursements.hbs
static/templates/filings/candidate.hbs
static/templates/filings/pac.hbs
static/templates/independent-expenditures.hbs
static/templates/receipts.hbs

This reduces some of the boilerplate around table panel rows--we move the elements and classes to a block helper, and the person writing the templates only has to think about content. I didn't update every last row--I will if we agree that the change is worthwhile.
cc @noahmanger

Add block helper to reduce panel boilerplate.

---

templates/election-lookup.html

Eliminates `e.g.` which users don't often understand
Adds a more flavorful ZIP

Content only: Copyedit to ZIP code autotext

---

README.md

Now, if you copy a command from the readme with triple-click control-C,
you can paste it directly into a shell and run it.
Command:
python - README.md <<EOF
import re
import sys
fn = sys.argv[1]
lines = None
with open(fn) as f:
lines = f.readlines()
with sys.stdout as f:
for line in lines:
f.write(re.sub(r"^( +)\\$ ", r"\1", line))
EOF

Remove $'s from commands in readme for pastability

---

openfecwebapp/templates/partials/navigation.html

Somewhere along the line the calendar link reverted to its disabled state. This restores it.

Enabling calendar

---

package.json

This changeset updates the dependency to `fec-style` to allow for retrieving the latest patch level.
/cc @noahmanger

Updating the pinned version of fec-style

---

karma.conf.js

By default, browserify only applies the requested transforms to source files, not to dependencies. This patch uses the global flag to apply the handlebars transform to dependencies too.
cc @noahmanger

Use global hbsfy transform in tests.

---

openfecwebapp/templates/search.html

"Funds" is a weird word. And in this case, the H5 is followed by a dollar sign, which I think is a clear explainer that we are talking about money. 
This PR proposes that rather than saying "Funds raised" and "Funds spent" we say only "Raised" and "Spent."
Related: https://github.com/18F/openFEC-web-app/issues/1158
Content only. Let me know if anyone has questions or concerns.

Omits "funds"

---

bin/run.sh
openfecwebapp/app.py

This changeset addresses an issue I introduced with the last commit to update the deployment.  I tried to account for this by explicitly setting the app name to `openfecwebapp` in the Flask app initialization, but by moving it into `app.py` this still ultimately did not work.  I have changed this to simply use the module name itself as is standard practice and fixed the `gunicorn` initialization in `bin/run.sh` to properly account for the new namespace.
/cc @LindsayYoung

Fixes the app initialization with gunicorn

---

openfecwebapp/routes.py
openfecwebapp/templates/candidates-single.html
openfecwebapp/templates/committees-single.html
openfecwebapp/templates/datatable.html
openfecwebapp/templates/election-lookup.html
openfecwebapp/templates/elections.html
openfecwebapp/templates/macros/breadcrumbs.html
openfecwebapp/templates/macros/page-header.html
openfecwebapp/templates/partials/hero.html
openfecwebapp/templates/search-results.html
openfecwebapp/templates/search.html

Adds simple breadcrumb navigation pattern to data pages through a macro.
The macro automatically adds the `page-header` bar, and by passing the page title and array of breadcrumbs, generates the breadcrumb list.
It also accepts a `show_search` param to show the search and `search_type` to set the type of search (candidates or committees).
Goes with:
- https://github.com/18F/fec-style/pull/307

Adds breadcrumbs

---

karma.conf.js
tests/unit/vendor/tablist.js

1. Configures Browserify to process tablist.js.
2. Adds basic tests for tablist.
Part of step two of #1052.

Adds tests for tablist

---

static/templates/electionZipWarning.hbs

Per the suggestion in https://github.com/18F/FEC/issues/292 , this
directs users directly to the house.gov results page for the zipcode
they entered.
Fixes https://github.com/18F/FEC/issues/292

Adds a more specific zipcode lookup link

---

.cfignore
.gitignore
README.md
manifest_dev.yml
manifest_feature.yml
tasks.py

This allows us to have the web app deployed to the feature space. Thanks @anthonygarvan for doing the hard work of setting up services in the feature space.
I've also tweaked the way `invoke deploy` works so that providing your password is not required. You can just login with `cf login` normally and run `invoke deploy --space feature`.
cc @ccostino @noahmanger

Add a manifest for the feature space

---

openfecwebapp/app.py

This will configure the logger to send output to stdout, and therefore `cf logs` and logs.cloud.gov.

Configure logging to stdout

---

package.json

This changeset brings the `fec-style` dependency up to date with the latest release.

Bump fec-style version to support ~1.10

---

static/js/pages/electioneering-communications.js

We moved the filter panel and widget initialization code to tables.js, but forgot to remove it from here.

Removing duplicate code

---

openfecwebapp/templates/macros/disclaimer.html
openfecwebapp/templates/partials/candidate/financial-summary.html
openfecwebapp/templates/partials/candidate/other-spending-tab.html
openfecwebapp/templates/partials/committee/independent-expenditures-tab.html
openfecwebapp/templates/partials/elections/other-spending-tab.html

This is a partner PR for https://github.com/18F/fec-style/pull/345 and adjusts type treatments in instances  of notes about the information on the data side. It makes some language consistent (removes "Note:" because we had been using it in some places, but not others) and changes one font style.
**After**
**Before**
cc @emileighoutlaw @noahmanger

Typesetting and note text adjustments

---

openfecwebapp/templates/legal-doc-search-results.html
openfecwebapp/templates/legal-search-results.html
static/js/modules/tables.js

This subclass is being dropped from fec-style. This should be merged first, before bumping the fec-style version.
Related: https://github.com/18F/fec-style/pull/342

Remove .results-info--top

---

openfecwebapp/api_caller.py
openfecwebapp/routes.py
openfecwebapp/templates/legal-doc-search-results.html
openfecwebapp/templates/legal-search-results.html
openfecwebapp/templates/macros/breadcrumbs.html
openfecwebapp/templates/partials/legal-filter.html
openfecwebapp/templates/partials/legal-search-results-advisory-opinion.html
openfecwebapp/templates/partials/legal-search-results-regulation.html
openfecwebapp/views.py
static/js/pages/committee-single.js

This introduces the Advisory Opinion search page. Eventually this document-specific search page would be used to implement Regs and MURs search as well.
https://github.com/18F/fec-eregs/issues/52
**search results**
**pagination**
Changes to fec-style coming soon.

Create a document-specific legal search page

---

openfecwebapp/templates/search.html

Content only :)
This fixes the ZIP code placeholder text match what exists here: https://github.com/18F/openFEC-web-app/blob/2d9d56aa485a7a06b4a1c04a5e8f289cc2b19371/openfecwebapp/templates/election-lookup.html
Which has been _bugging me_. 
Also eliminates `e.g.,` which I'm trying to avoid as much as possible.
_h/t @ccostino for helping me find this in the code!_

Updates placeholder

---

openfecwebapp/templates/partials/committee-totals-presidential.html

Content only.
This fixes a capitalization problem and relabels "Federal funds" as "Presidential public funds" in our summary chart.
h/t @amykort for noticing this inconsistency. 
Anyone can review and merge.

Data microcopy

---

openfecwebapp/templates/partials/communication-costs-filter.html

This is a content only update. Anyone can review.
This updates the communication costs filter so that it says "spender." This will help us unify our content with what's already on the electioneering communications and IE filter pages.
Resolves: https://github.com/18F/openFEC-web-app/issues/1262#issuecomment-225050785
cc @LindsayYoung

Updates "spender" filter

---

bin/post_compile

This script should have been removed as a part of https://github.com/18F/openFEC-web-app/pull/1270.
h/t to @adborden for catching this.

Removing extra build script

---

openfecwebapp/templates/macros/filters/date.html

**DON'T MERGE YET**
Part of https://github.com/18F/openFEC/issues/1735
Dependent on https://github.com/18F/openFEC/pull/1736
This changeset renames the field we originally went with for partitioning the itemized schedule A and B tables. We had received feedback that `transaction_year` was a bit confusing and have decided to go with `two_year_transaction_period` instead to be more descriptive of what this value represents.
/cc @LindsayYoung, @jontours, @noahmanger

[DON'T MERGE YET] Rename transaction_year field

---

openfecwebapp/templates/macros/filters/date.html

Part of https://github.com/18F/openFEC/issues/1735
Dependent on https://github.com/18F/openFEC/pull/1736
This changeset renames the field we originally went with for partitioning the itemized schedule A and B tables. We had received feedback that `transaction_year` was a bit confusing and have decided to go with `two_year_transaction_period` instead to be more descriptive of what this value represents.
/cc @LindsayYoung, @jontours, @noahmanger

Rename transaction_year field

---

package.json

A small update to account for the latest version of https://github.com/18F/fec-style.
/cc @noahmanger, @adborden

Update fec-style to 2.5.1

---

openfecwebapp/templates/landing.html

- Updates the example text to use real pairs of a committee and candidate, with their ID numbers.
@emileighoutlaw 
Resolves https://github.com/18F/openFEC-web-app/issues/1297

Updates example text to use real, complete examples

---

openfecwebapp/templates/advanced.html

I took a stab at adding the advanced data content. There were lots of `<div>`s on this page, so please let me know if I put these paragraphs in the wrong section. 
This PR:
- Adds content to "Candidates," "Committees," "Receipts," "Spending," and "Filings"
- Links terms in the new content to the glossary
- Makes "Filings and Reports" header "Filings," which is our preferred blanket term for all types of filings (this is also explained in the section's new subtext).
cc @noahmanger @jenniferthibault

Adds advanced content

---

openfecwebapp/templates/macros/tables.html
openfecwebapp/templates/partials/committee/financial-summary.html
package.json

Adjusts the totals tables on committee pages to look like this:
Depends on https://github.com/18F/accordion/pull/8 and https://github.com/18F/fec-style/pull/400
Resolves https://github.com/18F/fec-style/issues/321

Adjusting totals table accordions

---

static/js/modules/bar-charts.js

Fixes a bug on /data where hovering over the "Spending" chart and then hovering over the "Raising" chart would cause the page to crash.

[MERGE WITH GITFLOW] Emptying tooltip on hide

---

openfecwebapp/templates/partials/elections/candidate-comparison-tab.html
static/js/modules/column-helpers.js
static/js/pages/committee-single.js

As reported in https://github.com/18F/openFEC-web-app/issues/1268, we used different language and logic for the contribution size buckets on committee pages vs election pages. This makes them consistent.
On committee pages:
On election pages:
Resolves https://github.com/18F/openFEC-web-app/issues/1268
CC @LindsayYoung

Using the correct numbers and labels for size buckets

---

openfecwebapp/templates/legal-doc-search-results.html
openfecwebapp/templates/legal-search-results.html

All our other notifications on use the term "search" instead of "query." So this is just a small copyedit for consistency!
cc @adborden (or anyone else really; this is a super fast, content-only PR)

Makes "query" "search"

---

package.json

This changeset accounts for the latest `fec-style` release (2.6.1).

Bump fec-style version to 2.6.1

---

openfecwebapp/templates/layouts/main.html

- Edits the dash to a pipe
- Edits "beta.FEC.gov" to "FEC"
resolves https://github.com/18F/fec-cms/issues/385
cc @noahmanger 
h/t @edmullen for noting the style inconsistency

Page title content update

---

openfecwebapp/templates/advanced.html

Adds following acronym per our style guide. 
A super tiny edit that I wanted to get in before I forgot about it. 
Content only.

Adds following acronym

---

static/js/pages/elections.js

Depends on https://github.com/18F/openFEC/pull/1825
Fixes #1355 
This changeset adds a missing flag to the query that is used for pulling the candidates for the fundraising comparison section.  It was missing the `sort_null_hide` parameter.
/cc @noahmanger, @jenniferthibault

Fix fundraising comparison on election page

---

openfecwebapp/templates/macros/filters/text.html
openfecwebapp/templates/macros/filters/typeahead-filter.html
static/js/modules/helpers.js
static/js/modules/tables.js
static/js/pages/elections.js
tests/unit/modules/tables.js

This adds support for removing the loading class and adding success / error classes to filters. 
I was thinking about where the best place for these calls to live was and I think it's here rather than having event listeners on the individual filter elements, but would like @xtine 's thoughts.
Depends on https://github.com/18F/fec-style/pull/435
cc @xtine

Removing loading state / setting success state

---

static/js/modules/tables.js

Super crude fix for a bug where `$label` selection was also including the `<div class="overlay is-loading">`, which meant that the message was being appended after the overlay, instead of whatever was the loading element for the filter.
This should be refactored, but it will do the trick for now.
cc @xtine

[MERGE WITH GITFLOW] Don't include the loading overlay in the selector

---

runtime.txt

With the recent cloud.gov update, the python buildpack no longer supports python 3.4.3, so let's upgrade.
https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.5.8

Bump python for cloud foundry

---

openfecwebapp/templates/partials/disbursements-filter.html
openfecwebapp/templates/partials/operating-expenditures-filter.html

Hey @noahmanger and @xtine! 
I noticed that the filters for disbursements and operating expenditures weren't currency inputs. Like so:
I was going to file an issue, but I thought I'd try to fix it myself (I want to be better at this kind of thing!) All that's to say I'm 50/50 on whether I did this perfectly or completely wrong. 
<3 ,
Emileigh

Filter currency

---

manifest_dev.yml
manifest_feature.yml
manifest_stage.yml
openfecwebapp/config.py
openfecwebapp/routes.py
openfecwebapp/templates/legal-search-results.html
openfecwebapp/templates/macros/legal-search.html
openfecwebapp/views.py

- Moves the feature flag to the credentials service, as per https://github.com/18F/fec-cms/pull/401
- Simplifies the feature flag variable using `config.features` directly in templates

Move feature flag to credential service

---

openfecwebapp/templates/datatable.html
static/js/modules/tables.js

Fixes padding on data-table pages vs legal resources search pages. Data tables are now wrapped in a `.data-container__table` class which only has padding on the left (and 0 padding on small screens). Search results have `.data-container__body` which has padding on both sides (including mobile).
cc @adborden 
Requires https://github.com/18F/fec-style/pull/469

Changing class from data-container__body to data-container__table

---

openfecwebapp/api_caller.py
openfecwebapp/templates/legal-advisory-opinion.html

The current AO canonical page has a "Final Opinion" button that does not pull up the Final Opinion.
This PR addresses that and the edge cases where there is no Final Opinion.

updating URL for Final Opinion

---

static/js/modules/helpers.js
static/js/modules/tables.js

Based on the discussions on #1397, update filter success messaging to more/less:
Include a message after filter errors:
Goes along with 18F/fec-style#478
cc: @noahmanger

Update filter messaging

---

openfecwebapp/templates/partials/candidates-office-filter.html

Office is now part of the `table_context` object rather than a
standalone template var

Fixing candidate office filter

---

openfecwebapp/templates/partials/filters/efiling.html

Fixes the bug that was causing the broken filings and reports pages.

Adding the missing data attribute for the efiling filter

---

openfecwebapp/templates/partials/legal-search-results-statute.html

Per https://18f.slack.com/archives/fec-partners/p1467229654000403 should be `U.S.C.` instead of USC.

update copy to be U.S.C.

---

openfecwebapp/templates/layouts/legal-doc-search-results.html

Currently the disclaimer is on the legal resource landing pages.  But we should have the standard beta disclaimer on our search results pages as well.

add disclaimers to search results pages

---

openfecwebapp/templates/legal-statutes-landing.html

Depends on https://github.com/18F/fec-style/pull/493
@jenniferthibault pointed out that the document thumbnail grid should not overflow the text width.

Constrain document thumbnail grid to text-width

---

openfecwebapp/templates/layouts/main.html

Adds the print logo from https://github.com/18F/fec-style/pull/496
Because certain browsers don't render background images it has to be included as an `img`.

Adding printer-only logo

---

openfecwebapp/templates/landing.html

For @ccostino to review:
This fixes the typo in the chart copy, but I _also_ found the same typo in a style class surrounding it. Correcting the typo in the class adds more space between the chart elements, which is OK.

[MERGE WITH GITFLOW]: Hotfix/chart typo

---

openfecwebapp/templates/macros/filters/date.html

Date filters that are not bound to two-year transaction periods will not have a radio selection but  simpler beginning/end input date fields. Relies on 18F/fec-style#517
Issue: 18F/fec-style#501

Simplify DateFilter for non two-year transaction periods

---

package.json

Makes use of the new version of the glossary panel that sets focus on the element that opened the glossary.
cc @xtine

Pinning to new minor update of glossary

---

openfecwebapp/templates/404.html

404 page always shows up with the title "| FEC". This changes it to "Not found | FEC"

Add title to 404 page

---

openfecwebapp/templates/macros/overviews.html

This removes the spaces around the n-dash in the controls for the landing charts so they now look like:
There's still some window-widths where the length of the title forces the next button to break on a new line, but with this change it's less common. I think we need a better solution ultimately but this should hopefully help in the mean time. 
cc @jenniferthibault @PaulClark2

Remove spaces around n-dash and use real n-dash

---

openfecwebapp/templates/layouts/main.html

Updates to footer section:
- Rearrange links to accommodate new Press section
- Add social media links (right now missing Facebook, can't find link)
Header:
- Remove contact link
Issue #503, relies on 18F/fec-style#524

New Footer Updates

---

openfecwebapp/templates/layouts/legal-doc-search-results.html
openfecwebapp/templates/macros/legal.html
openfecwebapp/templates/macros/missing.html
openfecwebapp/templates/partials/search-results-alternatives.html
static/templates/electionNoResults.hbs
static/templates/tables/noData.hbs

While I was looking for example patterns for https://github.com/18F/openFEC-web-app/issues/1598 I looked back to our pattern design work in https://github.com/18F/fec-style/issues/266#issuecomment-214425298 and noticed that when I was reviewing the implementation in https://github.com/18F/openFEC-web-app/pull/1205 I missed something. We placed many `alert` style messages where we had intended to place `no-icon` style messages. The slightly angrier tone was picked up by Jeff in this issue: https://github.com/18F/FEC/issues/471
(cc @emileighoutlaw )
This PR replaces these instances with the `no-icon` message pattern.
**New**
**Before**
@noahmanger : did I do this right?

Changes message patterns for no data instances

---

openfecwebapp/templates/legal-advisory-opinions-landing.html
openfecwebapp/templates/legal-enforcement-landing.html
openfecwebapp/templates/legal-statutes-landing.html

This updates the enforcement landing page design to include the required legal citations from OGC in https://github.com/18F/fec-eregs/issues/282
- There are a few open content questions for @emileighoutlaw to answer in that issue before this gets merged in
- I'd also like to pair with @noahmanger or @adborden to finesse a few lingering spacing issues within this layout. That will probably require a PR to `fec-style` which I haven't started.
- It would be really really nice to include the search bar patterns in the style guide while we're looking at them, but that's not a deal-breaker :bowing_woman: 
**Desktop**
**Small screens**

Updates landing page designs

---

openfecwebapp/templates/partials/committee/disbursements-tab.html
openfecwebapp/templates/partials/committee/filings-tab.html
openfecwebapp/templates/partials/committee/financial-summary.html
openfecwebapp/templates/partials/committee/receipts-tab.html

Fixes an issue where the buttons in headings were breaking onto new lines instead of being floated to the right like: 
cc @jenniferthibault

Adding the correct class to headings with action

---

static/templates/tables/exportWidget.hbs

Uses the new `.tooltip--right` style to ensure that the tooltip is visible and right aligned. 
Requires https://github.com/18F/fec-style/pull/546
Resolves https://github.com/18F/openFEC-web-app/issues/1632

Adding tooltip--right to export tooltip

---

openfecwebapp/templates/macros/overviews.html

Adds a link to the glossary definition for "Other groups":
Resolves https://github.com/18F/fec-cms/issues/523
Requires https://github.com/18F/fec-style/pull/551
cc @emileighoutlaw

Adding link to other groups definition

---

openfecwebapp/templates/advanced.html
openfecwebapp/templates/candidates-single.html
openfecwebapp/templates/committees-single.html
openfecwebapp/templates/landing.html
openfecwebapp/templates/layouts/legal-doc-search-results.html
openfecwebapp/templates/legal-archived-mur.html
openfecwebapp/templates/legal-search-results.html
openfecwebapp/templates/macros/disclaimer.html
openfecwebapp/templates/macros/filters/date.html
openfecwebapp/templates/partials/candidate/financial-summary.html
openfecwebapp/templates/partials/committee/financial-summary.html
openfecwebapp/templates/partials/datatable-modal.html
openfecwebapp/templates/partials/search-results-alternatives.html
openfecwebapp/templates/partials/warnings.html
openfecwebapp/templates/search-results.html
static/js/modules/column-helpers.js
static/templates/candidateStateMap.hbs
static/templates/electionResult.hbs

"View" generally isn't an ideal word for interface copy, because it can feel exclusionary to folks who use screenreaders and aren't "viewing" the text. 
Additionally, what we mean by "view" can vary depending on the context. This PR attempts to make our content more accessible and descriptive by changing the word "view" into one of the following:
- `Show` when we mean “display” information on the same page
- `Open` when we mean “opening” a document or taking users to a new page
- `Access` when we mean “making contact with” or “gaining access to" information
- `Check out` in the rare instance when we are offering alternative search pathways
This PR also contains some edits to improve the consistency of our results ranges. Sometimes we had "Viewing XX-XX of XXX results." Sometimes we had …

Make "view xxx" content more accessible

---

package.json

A bump for fec-style to fix the static chart image background placeholders.

[MERGE WITH GIT FLOW] Updating fec-style to 5.7.1

---

static/js/modules/columns.js

This adds back the `pdf_url` column which was replaced by `document_type` which includes the button to download different versions of a report. This is needed by the committee page filings table, which is currently too narrow to support the button. This fixes an error in production, but we’ll want to come up with a better solution later.
cc @LindsayYoung

[MERGE WITH GITFLOW] Hotfix/fix committee tables

---

static/templates/reports/candidate.hbs
static/templates/reports/ie-only.hbs
static/templates/reports/pac.hbs

I'm afraid "Means filed" might sound a little too... mean. This changes the content to "Filing method." 
Sound okay to y'all— @noahmanger @xtine ?

Filing method

---

openfecwebapp/templates/partials/filters/efiling.html

One of our UI consistency decisions was to use the phrase "electronic filings" rather than the more jargon-y "e-file" or "eFile" whenever possible.
Content only.
Partially resolves: 18F/fec-cms#585

Electronic filing

---

openfecwebapp/templates/legal-current-mur.html

Use the following conventions:
- 11 CFR 112.1(a)
- 52 U.S.C. §30123
- Periods and section symbol for U.S.C.
- No period or section symbol for CFR
- Linking only the part of the citation that follows CFR or U.S.C.
Fixes 18F/openFEC#2069
https://github.com/18F/openFEC/issues/2069

Format citations according to type

---

openfecwebapp/routes.py
openfecwebapp/templates/legal-advisory-opinions-landing.html

This updates the AO landing page as part of https://github.com/18F/fec-eregs/issues/290
In order to get the feeds of latest and pending AOs, this requires the API work from https://github.com/18F/openFEC/pull/2091 as well as upcoming work to allow filtering by document type. 
It's also dependent on https://github.com/18F/fec-cms/pull/654 in order for links to that page to work.
---
Changes to make:

Starting advisory opinions landing page update

---

openfecwebapp/templates/macros/overviews.html

@xtine — I wasn't paying close enough attention, and two of the ranges were in tables.
Therefore they shouldn't use the word "to". 
This PR reverts the "to" back to a "-"
Two tiny content changes. Sorry 😭😭😭

Reverting range

---

openfecwebapp/api_caller.py
openfecwebapp/routes.py
openfecwebapp/templates/legal-advisory-opinions-landing.html
openfecwebapp/views.py

I forgot to remove the mock data from the new AO landing page before it was merged in, so this removes that and also comments out the pending AO section. I could remove that entirely if we'd prefer to not have commented code, but that should be done soon. 
The remaining task here is to add the last two months of AOs to this page. I'm having local API trouble so can't do this at the moment, but should be able to add on Friday.

Prepare AO landing page

---

openfecwebapp/templates/macros/legal.html

This makes the date fields required. If they are submitted as empty, webargs throws a parse error that cannot be handled by setting missing=None (since it is not missing, but actively set to an empty string). Long term solution here is to replace native submit functionality with a js submit.

making dates required to avoid parse error

---

openfecwebapp/api_caller.py

This changeset addresses a small issue I noticed with the code that handles the sorting of MURS participants by type.  The tests were failing due to an `OrderedDict` being modified during iteration, so I moved the code that removed empty roles outside of the loop over the `OrderedDict` items.  Generally speaking, inserting/deleting items in a container/collection-like structure while iterating over it will produce unpredictable results and is not supported.  I thought `OrderedDict`s were a bit different in that regard, but apparently not due to the failing test I was seeing.  At least in Python 3, the same underlying dictionary views are used, which mentions that a `RuntimeError` can occur in this situation:  https://docs.python.org/3.5/library/stdtypes.html\#dictionary-view-objects
/cc …

Improves sorting of MURS participants by type

---

openfecwebapp/api_caller.py

`respondents` is already available as a property on the MUR.

Remove redundant code

---

openfecwebapp/templates/legal-advisory-opinions-landing.html

The new AO process page in this upcoming release is a CMS page rather than a static view with a hard-coded URL. This updates the link to go to the correct place.

Fixing link to AO process page

---

openfecwebapp/constants.py

I noticed that what we're currently calling the disbursement "purpose" column is in fact the disbursement "description" (different fields), so this renames it.

Names the disbursement description column correctly

---

openfecwebapp/templates/partials/candidates-filter.html

Renames the param name of the "election year" filter to `cycle` to fix the issue of missing candidates.
Fixes https://github.com/18F/openFEC/issues/2197

Renaming param to correct value

---

openfecwebapp/templates/advanced.html

Adds link to Advanced Data page under the spending section:

Adds link to the party coordinated expenditures data table

---

static/js/modules/election-lookup.js
tests/unit/modules/election-lookup.js

This is a temporary hack to remove presidential elections from the election lookup tool on non-presidential years. Eventually this will be handled by the API but in the mean time this will get rid of a glaring error.

Removing presidential results that with incorrect dates

---

openfecwebapp/templates/legal-advisory-opinions-landing.html
openfecwebapp/views.py
tests/unit/test_legal_search.py

https://fec-stage-proxy.18f.gov/data/legal/advisory-opinions/ is currently failing because this view and template hadn't been refactored to account for the new AO schema. This makes the necessary fix. 
cc @vrajmohan

Fixes rendering on ao landing page

---

openfecwebapp/constants.py
openfecwebapp/templates/macros/tables.html
openfecwebapp/templates/partials/committee/new/financial-summary.html

This makes the last change needed to close out this issue: https://github.com/18F/openFEC-web-app/issues/1832
It adds support for linking financial summary labels to their glossary definitions and for linking numbers to views of the itemized transactions. Because of the filters we have available, we can only link to total receipts, individual contributions, disbursements, and independent expenditures, but we can add more later.
Happy to receive feedback on the best way to do this. This seemed like maybe a weird use of `constants.py` so if there's a better way, by all means. 
It also adds support for the fields that @jontours is adding in https://github.com/18F/openFEC/pull/2215

Adding links to itemized transactions and glossary definitions

---

.travis.yml
README.md
gulpfile.js
manifest_dev.yml
openfecwebapp/app.py
openfecwebapp/config.py
openfecwebapp/views.py
package.json
requirements.test.txt
requirements.txt
runtime.txt
static/js/init.js
tasks.py

This changeset updates some of the tooling and infrastructure in the web app to bring things up to date.  It focuses more on the backend and Python as opposed to the front-end components, but includes the following:
* Cleanup of .travis.yml
* Updates fec-style to latest release (7.7.0)
* Updates a handful Python dependencies
* Cleanup of `invoke` tasks
* Removal of all references to Sentry/Raven
* Updates cloud.gov Python runtime to 3.5.3
* Fixes reference to API in the `manifest_dev.yml` config
* A handful of `README.md` updates
The Travis cleanup includes updating nvm to make use of the latest stable release of Node.js, which I have been running locally for a while now with no issues.
I also attempted to run things in Python 3.6, but one or two of our dependencies seem to be struggling …

Update some of the backend tooling for the web app

---

openfecwebapp/api_caller.py

Small fix to prevent key errors that occur if API is down. This checks to make sure there's a `results` key in the `response` and otherwise returns `None`. 
Let me know if there's a better way to do this.
cc @LindsayYoung 
Resolves https://github.com/18F/openFEC-web-app/issues/1894

Preventing key errors if the API is down

---

openfecwebapp/templates/partials/candidate/individual-contributions.html
openfecwebapp/templates/partials/committee/disbursements.html
openfecwebapp/templates/partials/committee/receipts.html
static/js/pages/candidate-single.js
static/js/pages/committee-single.js

Because the "purpose of disbursement" aggregate logic is unreliable, @PaulClark2 [requested](https://github.com/18F/openFEC/issues/1833#issuecomment-291473162) disabling those tables on committee pages for now, so this PR does that.
I also took the opportunity to add a feature from the original designs that we just hadn't gotten to yet: adding the tables of itemized contributions and disbursements:

Remove purpose of disbursement and add itemized tables

---

openfecwebapp/api_caller.py
openfecwebapp/views.py

This fixes the conditional logic when rendering candidate pages so the pages don't break if the candidate doesn't have financial totals for the selected cycle.
To verify, make sure this page works: http://localhost:3000/candidate/P80001571/?election_full=true&cycle=2020

Adding conditionals for cases when candidates don't have totals

---

openfecwebapp/templates/partials/site-orientation.html

Uses "Help for candidates and committees":

Banner edit

---

openfecwebapp/routes.py

This fixes the issue of 404s for candidates who ran for special elections in odd years. It adds a check for trying to set `next_cycle` to an odd value, and if so, falls back to the `cycle`, which corresponds to the two-year period for which the committee has financial activity. It then also sets `election_full` to false. 
This makes sense in these cases and fixes the reported bugs with Ossof and Halvorsen, but paging @LindsayYoung to double-check my logic here.

Fixes an issue for candidates who ran in odd years

---

openfecwebapp/templates/legal-advisory-opinions-landing.html
openfecwebapp/templates/partials/legal-search-results-advisory-opinion.html
static/js/legal/LegalSearch.js

A couple non-urgent copyedits for capitalization consistency:
fec.gov --> FEC.gov
Advisory Opinions --> advisory opinions
Content only. Anyone can review 🌞

Capitalization copyedits

---

package.json
static/js/init.js

This takes advantage of a small change in the accordion library in order to allow multiple accordions on the same page. It just updates the version number (did it for the glossary, too, which I just bumped to 1.0.0), and now passes in an element as the first arg of the accordion constructor.

Adding support for accordion library v1.0.0

---

openfecwebapp/templates/legal-advisory-opinion.html

cc @jenniferthibault I tightened up the spacing a little by changing `<p>`'s to `<div>`'s. If you or @nickykrause take a look to review, you can just recommend existing classes to apply (preferred) or if we really need to we can make a new class (or maybe adding a new utility would be better?).

adding templating for reg and statute citations

---

manifest_base.yml

This changeset adds a missing env var to our base manifest to ensure that the transition site URL does not get lost on subsequent deploys.

Add missing transition URL env var

---

openfecwebapp/templates/partials/navigation.html

This fixes the mega menu in Safari by adding tabindex to the links. 
The issue is that the mega menu calls the click handler when the triggering element has focus. Chrome automatically adds focus to an element when you click it, but Safari doesn't unless there's a tabindex. 
Also requires https://github.com/18F/fec-style/pull/688

Adding tabindex to nav links

---

openfecwebapp/config.py

This changeset updates all env var references to use `env.get_credential` to ensure that an environment variable is always found.

Update env var references

---

static/js/legal/LegalSearch.js

This fixes the AO search in Internet Explorer by replacing an unsupported ES6 method (`Object.assign()`) with Underscore's `_.extend()` which for this purpose does the same thing. 
It also removes the API key from being included in the browser query string for prettier URLs (and similar to how we handle it on other parts of the site). 
cc @anthonygarvan

[MERGE WITH GITFLOW] Hotfix/ie aos

---

openfecwebapp/api_caller.py

What we initially thought was incorrect coverage dates for the full election totals on candidate pages turned out that it wasn't showing the full election totals at all. The API expects the parameter to be `full_election` but the app incorrectly was sending `election_full`. Fixing that fixes the totals and the coverage dates:
Resolves https://github.com/18F/openFEC-web-app/issues/2008

Use full_election for totals

---

openfecwebapp/routes.py
openfecwebapp/templates/macros/filters/years.html
openfecwebapp/templates/partials/candidates-filter.html
openfecwebapp/templates/partials/candidates-office-filter.html
openfecwebapp/templates/partials/committees-filter.html
openfecwebapp/templates/partials/filings-filter.html
openfecwebapp/templates/partials/independent-expenditures-filter.html
openfecwebapp/templates/partials/reports-filter.html
static/templates/receipts.hbs

As reported in https://github.com/18F/FEC/issues/4032, the [House Candidates](https://beta.fec.gov/data/candidates/house/) page is missing the state (and district) filter. I looked into it and the template code was already there, but it was using the wrong variable to check the office. So this is just a small fix to restore the original designed functionality:
Resolves https://github.com/18F/FEC/issues/4032
This also includes a small fix to restore the details panels when looking at raw receipts data.

Pass office to template to restore correct filters

---

package.json
static/js/modules/download.js

This updates jQuery to the latest version. I clicked through the site and everything seems to be working. I also ready through the [upgrade guide](https://jquery.com/upgrade-guide/3.0/#overview) and checked for instances of the things they warned about and I didn't find anything concerning.
~The one snag is that a single test is failing, which seems to perhaps relate to the change in the `$.Deferred()` implementation.~
~But I'm stumped, so I'd appreciate if someone else could take a look.~
Update: the test issue is resolved.

jQuery 3.2.1

---

openfecwebapp/templates/layouts/main.html

- Links to FOIA page
- Makes FOIA bottom link (so it's on the same latitude as Press; makes it easier to scan across)
- Links to strategy and budget page
These changes are also incorporated in fec-cms: https://github.com/18F/fec-cms/pull/1037
cc @noahmanger

Updates footer links

---

openfecwebapp/templates/macros/filters/election-filter.html
openfecwebapp/templates/partials/candidates-office-filter.html

In https://github.com/18F/openFEC-web-app/pull/2000/commits/2d98e0e5220ed64024244159488fc99eb203e360 I changed the cycle filter on the House candidates data page to be a multi-select dropdown. But that was a mistake; it should only be a single-select dropdown, because we only want to look at one period of data at a time. Allowing multiple leads to duplicate results.

Election year filter

---

openfecwebapp/templates/partials/committee/disbursements.html

This is a small but important hotfix to fix the display of itemized disbursements on committee pages. I initially misunderstood [this issue](https://github.com/18F/FEC/issues/4051), but what it was flagging is the fact that _all_ committee disbursements for _all_ committees are currently showing up on committee pages. This was because the javascript that makes the API call was looking for `data-committee` rather than `data-committee-id`. So this just fixes the data attribute and now the committee ID is passed through.

HOTFIX: Pass committee ID through for itemized disbursements

---

openfecwebapp/templates/advanced.html
openfecwebapp/templates/partials/meta-tags.html
package.json

This adds custom social and touch icons depending on the parent section you're in (data or legal).
Requires https://github.com/18F/fec-style/pull/699

Adding new social images based on parent

---

openfecwebapp/templates/advanced.html

The content owners agreed that we should change the presidential matching fund links from transition to classic.

Changed URLs on Advanced Data page

---

openfecwebapp/templates/partials/candidate/financial-summary.html
openfecwebapp/templates/partials/committee/financial-summary.html

This hides the coverage dates on candidate and committee financial summaries while we resolve the issue with the dates being wrong.

[MERGE WITH GIT FLOW] Hiding coverage dates

---

README.md

This replaces references to `betaFEC` with `the FEC`, `FEC.gov`, or `the new FEC.gov` as appropriate.

swap out beta references in README

---

openfecwebapp/templates/partials/committee/about-committee.html

This pulls in the candidate's party, state and district info onto a committee page, as requested in https://github.com/18F/FEC/issues/4118 and https://github.com/18F/openFEC-web-app/issues/1969
For president:
For house:
And senate:

Show more candidate info on cmte page

---

openfecwebapp/templates/macros/tables.html
openfecwebapp/templates/partials/candidate/financial-summary.html
openfecwebapp/templates/partials/committee/financial-summary.html

This passes through the value of the selected cycle to links to itemized receipts, disbursements and independent expenditures. It passes the value in as both `two_year_transaction_period` and `cycle` because receipts and disbursements use the former, and IEs use the latter, and there's not a problem passing a filter that isn't used.
Resolves https://github.com/18F/openFEC-web-app/issues/2077

Passing cycle value to links to itemized data

---

openfecwebapp/templates/partials/site-orientation.html

Update the "Start the tour" button for post-flip.
Relies on https://github.com/18F/fec-style/pull/720
https://github.com/18F/fec-cms/issues/1081

Update "Start the tour" button

---

static/js/modules/columns.js
static/js/pages/candidate-single.js
static/js/pages/committee-single.js
static/templates/reports/candidate.hbs
static/templates/reports/ie-only.hbs
static/templates/reports/pac.hbs
static/templates/reports/reportType.hbs

The committee filings table isn't manually sortable, since it uses a complex sorting query to get filings to display in a certain order. However, due to a quirk in the datatables library, it was rendering it as if the first column was sorting, which made it seem like you should be able to sort it in the other direction. This removes the apparent (but not functional) sort styling from the document description and receipt date columns:
Resolves https://github.com/18F/FEC/issues/4155
Resolves https://github.com/18F/openFEC-web-app/issues/2041
This also makes it so that reports tables only show links to PDFs if the `pdf_url` is actually present for a given report.
Resolves https://github.com/18F/FEC/issues/4158
---
This also fixes an issue we're experiencing with wonky column widths in …

Fixing sort problems on committee filing tables

---

openfecwebapp/api_caller.py

This removes the election year filter when showing top raising and spending candidates which means that candidates running in odd years will show up:
Resolves https://github.com/18F/FEC/issues/4169

Remove election_year filter for top raisers and spenders

---

openfecwebapp/templates/legal-advisory-opinions-landing.html

Per a discussion in Slack, this adds the AO number field to the AO landing page and also updates the help text to include an example in quotation marks:

Adding ao number field to landing page

---

openfecwebapp/constants.py
openfecwebapp/templates/partials/disbursements-filter.html
openfecwebapp/templates/partials/filters/disbursement-purpose.html
openfecwebapp/templates/partials/operating-expenditures-filter.html

This removes the disbursement purpose filter per the discussion in Slack. The logic behind this filter is still too complicated and inconsistent, and this functionality will soon be partially replaced by the line number filter.
cc @jwchumley

Removing disbursement purpose filter

---

openfecwebapp/templates/partials/candidate/raising.html
openfecwebapp/templates/partials/candidate/spending.html
openfecwebapp/templates/partials/committee/raising.html
openfecwebapp/templates/partials/committee/spending.html

In order to make clear to users what data is included in the raising and spending detailed tables on candidate and committee pages, this adds the coverage dates. Previously in this release we were adding simply transaction dates, which span the entire cycle; this can be confusing because it doesn't show which reports are actually included.
It also makes the "All transactions" tab the first, default-opened tab.
For example:

Show coverage dates on raising and spending tables

---

openfecwebapp/templates/partials/candidate/raising.html
openfecwebapp/templates/partials/committee/raising.html
openfecwebapp/templates/partials/committee/spending.html
static/js/vendor/tablist.js
tests/unit/vendor/tablist.js

This makes the "all transactions" tab the default opened tab. I meant to include this in https://github.com/18F/openFEC-web-app/pull/2127 but forgot to push before it was merged. 
It also makes a change to account for the fact that our tab names are changing with this release. Now, if a something like `?tab=receipts` is included in the URL (as would be the case if someone bookmarked that tab previously) the page will default to open the first tab, whatever that is. Previously it would instead show all tabs at once, which was wrong.

Show all transactions as first tab

---

openfecwebapp/templates/candidates-single.html
openfecwebapp/templates/partials/candidate/raising.html
openfecwebapp/templates/partials/candidate/spending.html

This fixes errors caused by trying to load certain template partials when a candidate page has no financial data. If there's no data, there is no `two_year_totals` template variable, which the `raising.html` and `spending.html` partials need. So this just doesn't show those tabs on candidates without financial data, which I think makes sense:
It also fixes a mistake from earlier where the coverage dates shown on the raising and spending pages were for the entire 4 or 6 year range, rather than just the two-years, which they should be.

HOTFIX: Only show raising and spending tabs if there's data

---

openfecwebapp/templates/partials/committee/raising.html
openfecwebapp/templates/partials/committee/spending.html

This is a companion fix to https://github.com/18F/openFEC-web-app/pull/2134 to only show coverage dates on committee pages if there's actual totals data.

HOTFIX: Only show coverage dates if there's totals data

---

openfecwebapp/templates/legal-advisory-opinions-landing.html
openfecwebapp/views.py
tests/unit/test_legal_search.py

We're currently showing _all_ recent AOs, including pending opinions, on the [AO landing page](https://www.fec.gov/data/legal/advisory-opinions/). This change correctly only shows AOs with final opinions or withdrawal requests.
h/t @jbucelato

[HOTFIX] Restrict recent AOs to only final opinions and withdrawals

---

openfecwebapp/templates/partials/candidate/other-spending-tab.html

This goes with the fix to make raw/processed filters retain filter values https://github.com/18F/fec-style/pull/736.
This fix is because the candidate filter for processed IEs uses candidate ID but the candidate filter for raw IEs uses candidate name (because the ID hasn't been coded yet). So this passes the candidate name through so that when clicking through from this link and then toggling to raw it will show up:

Pass candidate name in links to IE page

---

openfecwebapp/templates/macros/entity-pages.html
static/js/modules/columns.js
static/js/pages/committee-single.js

This adds coverage dates to the regularly filed reports table on committee pages:
And the raw filings table:
Resolves https://github.com/18F/FEC/issues/4217
It also rolls in an earlier requested change, which is to not show a version status on RFAIs, as they can't be amended:
Resolves https://github.com/18F/FEC/issues/3942
It also fixes the negative page number issue by accounting for the fact that image numbers switched from 11 to 18 digits in 2015. This adds the code to just check the length and if it's 18 digits, it slices it after the first 8, and if it's not, it leaves it alone:
Resolves https://github.com/18F/FEC/issues/4232
Resolves https://github.com/18F/openFEC/issues/2475

Feature/report coverage dates & RFAI N/A version status

---

openfecwebapp/api_caller.py
openfecwebapp/routes.py
openfecwebapp/templates/layouts/legal-doc-search-results.html
openfecwebapp/templates/legal-archived-mur.html
openfecwebapp/templates/legal-current-mur.html
openfecwebapp/templates/legal-search-results-advisory_opinions.html
openfecwebapp/templates/legal-search-results-murs.html
openfecwebapp/templates/legal-search-results-regulations.html
openfecwebapp/templates/legal-search-results-statutes.html
openfecwebapp/templates/partials/candidates-filter.html
openfecwebapp/templates/partials/legal-search-results-mur.html
openfecwebapp/views.py
static/js/legal/Filters.js
static/js/legal/LegalSearch.js
static/js/legal/SearchResults.js
static/js/legal/Tags.js
tests/unit/test_legal_search.py

This started as an endeavor to clean up some of the filter style notes that @jenniferthibault documented in https://github.com/18F/openFEC-web-app/issues/2141 and ended up rolling in a few other cleanup items.
First, it adds the correct classes to the AO search results so they mirror the other data tables.
Second, I updated the breadcrumbs across legal search results pages so that they include their immediate parent pages, as well as the main top-level legal resource page. This has been a small thing that's been driving me nuts.
Third, I removed a bunch of the old unnecessary server-side AO search results code, since it all happens client-side now. Mainly that involved refactoring the api caller functions to use `**kwargs` instead of a bunch of `ao_*` named arguments. 
Interestingly …

Legal search cleanup

---

openfecwebapp/templates/partials/individual-contributions-filter.html
openfecwebapp/templates/partials/receipts-filter.html

Now that https://github.com/18F/openFEC/pull/2365/ is in, we can add it to the front-end:
Resolves https://github.com/18F/openFEC-web-app/issues/2018

Adding zipcode filter

---

openfecwebapp/constants.py

This hides the net operating expenditures and net contributions numbers (and their child lines) as the underlying logic needs some work.
The cash summary portion of financial summaries now looks like:
Worth nothing that these numbers are only incorrect for certain committees, but when they're wrong they're also wrong in the classic viewer.

Hide net contributions and operating expenditures

---

static/templates/reports/candidate.hbs
static/templates/reports/ie-only.hbs
static/templates/reports/pac.hbs
static/templates/reports/reportType.hbs

Pending resolution of the discussion in https://github.com/18F/openFEC/issues/2226 , this adds links to the webpage version of reports:
The document title in the table now links to this webpage version if it exists, falling back to PDF if necessary.

Adding links to web views of reports

---

openfecwebapp/constants.py

The link to line number F3P-27A was incorrectly coded in the line number decoder, preventing the link from working.

[MERGE WITH GITFLOW] Hotfix/pres loans

---

static/js/modules/helpers.js

This resolves an issue where termination reports showed up as an amendment even though they were the original. This is because they have a filing number in their `amendment_chain`. This change adds special logic for termination reports so that the presence of an self-referential ID in their `amendment_chain` doesn't make it display as an amendment.
Resolves https://github.com/18F/FEC/issues/4341
Resolves https://github.com/18F/FEC/issues/4390
Resolves https://github.com/18F/FEC/issues/4388

[MERGE WITH GITFLOW] Hotfix/termination report amendment status

---

static/js/pages/candidate-single.js
static/js/pages/committee-single.js

This fixes an issue where the itemized tables on committee pages (and the disbursement table on candidate pages) wouldn't page through.
This is because itemized receipts and disbursement tables (which use `schedule_a` and `schedule_b` endpoints) use the `SeekPaginator` option, which paginates through using `last_index` rather than `page`. 
Resolves https://github.com/18F/FEC/issues/4416

Adding SeekPaginator to itemized tables on profile pages

---

openfecwebapp/templates/layouts/main.html
openfecwebapp/templates/partials/navigation.html

This is work to add the About menu to the main navigation of the openFEC-web-app: https://github.com/18F/fec-cms/issues/1139
Also updated footer
Dependent on fec-style PR here: https://github.com/18F/fec-style/pull/748

Added about menu item to main navigation

---

static/js/modules/columns.js

Now that `html_url` values are reliably populated by the API for filings this adds them to the tables so that the main document name is the web page URL:

Pass html_urls to the front-end

---

openfecwebapp/constants.py
openfecwebapp/templates/macros/filters/election-filter.html

This makes it so that on https://fec.gov/data/candidates/senate/ , the default time period is whatever the constant `DEFAULT_TIME_PERIOD` is set to (now, 2018). While on https://fec.gov/data/candidates/president/ it stays 2016.
Requires a tweak in fec-style.
Resolves https://github.com/18F/openFEC-web-app/issues/2228

Set default senate cycle to the current two year period

---

openfecwebapp/templates/layouts/main.html

We already have a public key in the env and already look it up in `config.py` so this just passes it through to the Javascript. 
Resolves https://github.com/18F/openFEC-web-app/issues/2234

Use public API key for client-side calls

---

static/js/pages/candidate-single.js
static/js/pages/committee-single.js

This fixes some bugs where transaction tables on candidate and commitee pages wouldn't paginate correctly. This is because we have two types of paginators: the default is `OffsetPaginator` which uses `page=X` to page through. Schedule A and B tables use `SeekPaginator` which uses the `last_index` value to page through. 
To test, verify that the itemized tables on [this page](http://localhost:3000/committee/C00580100/?tab=spending) and [this page](http://localhost:3000/candidate/P80001571/?cycle=2020&tab=raising) can page through.

[MERGE WITH GIT FLOW] Adding SeekPaginator to itemized tables on profile pages

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml

The issue with the "Home" link in the breadcrumbs not linking to the home page (https://github.com/18F/openFEC-web-app/issues/2244) appears to be due to a missing `FEC_CMS_URL` env variable. This adds it to the manifests for all three environments.
Resolves https://github.com/18F/openFEC-web-app/issues/2244

Adding cms_url to manifests

---

openfecwebapp/routes.py
openfecwebapp/templates/candidates-single.html
openfecwebapp/templates/elections.html
openfecwebapp/templates/landing.html
openfecwebapp/templates/partials/candidate/about-candidate.html
static/js/modules/election-form.js
static/js/pages/elections.js
static/styles/elections.scss
tests/unit/modules/election-search.js

I forgot to include actual links on this part of the data landing, so this adds them:
It also adds the correct link to the election page from candidate pages:
And updates the state + district selects on election pages to go to the page similar to how it works on the data landing page:
And last, I fixed an issue where not all district results were showing up when doing a state search by adding `per_page=100` to API calls for the election lookup. Resolves https://github.com/18F/openFEC-web-app/issues/2256

Add links to election pages from data landing

---

static/styles/entity.scss

The committee pages were missing styles for the data table panel and download widget. This adds them.

Add missing CSS files to candidate and committee pages

---

openfecwebapp/constants.py
openfecwebapp/templates/partials/candidates-filter.html
openfecwebapp/templates/partials/committees-filter.html
openfecwebapp/utils.py
package.json
static/js/modules/columns.js

Currently on staging, going to [Alabama Senate 2018](https://fec-stage-proxy.app.cloud.gov/data/elections/senate/AL/2018/), the cycle select shows 2021-2022, which is the date of the next election. 
This change adds Alabama to the 2018 Senate class.

Add Alabama to 2018 senate class

---

openfecwebapp/templates/partials/committees-filter.html

I just noticed that the "first filing date" filter on [the committees page](https://www.fec.gov/data/committees/?min_first_file_date=08%2F10%2F2017) is labelled incorrectly. It should be statement of organization, not statement of candidacy.

[MERGE WITH GIT FLOW] Fixing label on committee F1 filter

---

openfecwebapp/templates/legal-archived-mur.html
openfecwebapp/templates/legal-current-mur.html

Fixing styling issues with MUR pages by adding this to MUR templates:
{% block css %}
<link rel=“stylesheet” href=“{{ asset_for(‘dist/styles/legal-common.css’) }}” />
{% endblock %}

[MERGE WITH GITFLOW] Added legal-common.css to mur templates
